### ISSUE TITLE
Support for react-router 6.4.0

### ISSUE THREAD

**Issue by voodoocreation** [salvoravida/redux-first-history#95]
Hey team - was just wondering if there's any planned support for [`react-router` v6.4.0](https://github.com/remix-run/react-router/releases/tag/react-router%406.4.0)?

After attempting to migrate to their newer method of wiring up routes, it appears it requires a whole new provider to be used, which doesn't seem to require creating the `history` instance to provide it - I'm assuming it now does it internally. Not too sure what changes would be required within `redux-first-router` to support this new way of wiring up the router, but at present due to the internal abstraction of `history` within `react-router`'s new API it doesn't seem to be possible to integrate it with `redux-first-history`.

Any updates on this would be greatly appreciated 🙏

**Comment by salvoravida** [comment]
wip

**Comment by salvoravida** [comment]
@voodoocreation it seems working https://codesandbox.io/s/redux-first-history-demo-rr6-forked-8ihzv6?file=/src/App.jsx

Am I missing something?

**Comment by voodoocreation** [comment]
Yeah the old API still works in `>=6.4.0` - it was their newer API using `create...Router` methods rather than creating a `history` instance and passing it down. Some more info about that can be found [in their docs](https://reactrouter.com/en/main/routers/picking-a-router#using-v64-data-apis). For example, using `const router = createBrowserRouter();` and then providing `router` to their `RouterProvider` component (which is the new way of doing things, which doesn't support `history` being provided - presumably because the `create...Router` functions are doing that internally).

**Comment by voodoocreation** [comment]
You might have to look at the internals of those new methods to see how it's integrating with the history events to see what you'll need to bind to to get the Redux integration working. Fingers crossed it's still possible and isn't something they've obfuscated within those new methods 🤞

**Comment by bobsilverberg** [comment]
> @voodoocreation it seems working https://codesandbox.io/s/redux-first-history-demo-rr6-forked-8ihzv6?file=/src/App.jsx
> 
> Am I missing something?

I am trying this now with `react-router-dom v6.4.2`, and I'm getting an error from the react-router code after clicking on a `Link`. I am doing SSR, which might be contributing to it, but up to this point that wasn't an issue. The initial page renders fine, but when I click on a link on the client, I am getting `TypeError: locationProp is undefined`, which is coming from https://github.com/remix-run/react-router/blob/892238bee052177e78012167c088290b06400206/packages/react-router/lib/components.tsx#L315-L321. 

I have tried debugging this and I cannot figure out why `location` is fine, and defined, at that point when the page is initially rendered on the server, but after clicking a link on the client, `location` is no longer defined. It seems like when the `@@router/LOCATION_CHANGE` action is dispatched, the `Router` itself rerenders, and at that point `location` is undefined.

If anyone has any insight into what might be happening here, it would be appreciated.

**Comment by mogsdad** [comment]
I had a config working with `react-router-dom@6.4.2` and just broke with 6.4.3. The TypeScript errors point pretty clearly to [a change](https://github.com/remix-run/react-router/pull/9496) that added a new `encodeLocation` property to `History` in `@remix-run/router` as a "patch". This divergence presents another challenge for supporting react-router 6.4.

```
    src/app/components/inputs/__tests__/nav-link.test.tsx:55:20 - error TS2741: Property 'encodeLocation' is missing in type 'History & { listenObject: boolean; }' but required in type 'History'.

    55     <HistoryRouter history={history}>
                          ~~~~~~~

      node_modules/@remix-run/router/dist/history.d.ts:116:5
        116     encodeLocation(location: Location): Location;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        'encodeLocation' is declared here.
      node_modules/react-router-dom/dist/index.d.ts:51:5
        51     history: History;
               ~~~~~~~
        The expected type comes from property 'history' which is declared here on type 'IntrinsicAttributes & HistoryRouterProps'
```

**Comment by mashood05** [comment]
> I had a config working with `react-router-dom@6.4.2` and just broke with 6.4.3. The TypeScript errors point pretty clearly to [a change](https://github.com/remix-run/react-router/pull/9496) that added a new `encodeLocation` property to `History` in `@remix-run/router` as a "patch". This divergence presents another challenge for supporting react-router 6.4.
> 
> ```
>     src/app/components/inputs/__tests__/nav-link.test.tsx:55:20 - error TS2741: Property 'encodeLocation' is missing in type 'History & { listenObject: boolean; }' but required in type 'History'.
> 
>     55     <HistoryRouter history={history}>
>                           ~~~~~~~
> 
>       node_modules/@remix-run/router/dist/history.d.ts:116:5
>         116     encodeLocation(location: Location): Location;
>                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>         'encodeLocation' is declared here.
>       node_modules/react-router-dom/dist/index.d.ts:51:5
>         51     history: History;
>                ~~~~~~~
>         The expected type comes from property 'history' which is declared here on type 'IntrinsicAttributes & HistoryRouterProps'
> ```

Hi, are u able to find any solution for this thank u

**Comment by trmnl-cmdr** [comment]
I'm trying to choose a router for all my projects for the next few years and I'm thinking that the lack of activity on this issue makes react-router a deal-breaker if I'm including this package in my stack and want the newer features. Does that sound right? It doesn't seem like a solution is coming after 6 months of activity. Or are you just waiting to see where the dust settles on newer versions of the router?

**Comment by elina-codes** [comment]
Any updates on this?

**Comment by knownasilya** [comment]
Seems like making your own version of https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/index.tsx#L229 could work, where you allow passing in history?

**Comment by kale1d0code** [comment]
I've tried creating my own create...Router from copying the code from createBrowserRouter but passing in history as a curried function example

```
const createHistoryRouter = (history: History) => (
    routes: RouteObject[],
    opts?: DOMRouterOpts
  ): RemixRouter => {
    return createRouter({
      basename: opts?.basename,
      future: {
        ...opts?.future,
        v7_prependBasename: true,
      },
      history: history ?? createBrowserHistory({ window: opts?.window }),
      hydrationData: opts?.hydrationData || parseHydrationData(),
      routes,
      mapRouteProperties,
    }).initialize();
}
```

The issues I'm facing are.
my function is returning an object and not a react element (crash)

History from redux-first-history does not fully implement History from History (fixed with //@ts-expect-error)
length, scrollRestoration, state, pushState, replaceState are missing.

There is also a call to history.createURL within react-router
which is throwing an error as it states this method doesn't exist.

**Comment by kale1d0code** [comment]
I've had a bit more of a go at this by adding the missing functions that the @remix-run/router library expects (dependency of react-router) to the history instance im passing into my createHistoryRouter implementation.

example:

```
export function invariant(value: boolean, message?: string): asserts value;
export function invariant<T>(
  value: T | null | undefined,
  message?: string
): asserts value is T;
export function invariant(value: any, message?: string) {
  if (value === false || value === null || typeof value === "undefined") {
    throw new Error(message);
  }
}

const createPath = ({
  pathname = "/",
  search = "",
  hash = "",
}: Partial<Path>) => {
  if (search && search !== "?")
    pathname += search.charAt(0) === "?" ? search : "?" + search;
  if (hash && hash !== "#")
    pathname += hash.charAt(0) === "#" ? hash : "#" + hash;
  return pathname;
}

function createURL(to: To): URL {
  // window.location.origin is "null" (the literal string value) in Firefox
  // under certain conditions, notably when serving from a local HTML file
  // See https://bugzilla.mozilla.org/show_bug.cgi?id=878297
  let base =
    window.location.origin !== "null"
      ? window.location.origin
      : window.location.href;

  let href = typeof to === "string" ? to : createPath(to);
  invariant(
    base,
    `No window.location.(origin|href) available to create URL for href: ${href}`
  );
  return new URL(href, base)
};

const wrapHistory = (history: History): History => ({
  ...history,
  encodeLocation: (to: To) => {
    // Encode a Location the same way window.location would
    let url = createURL(to);
    return {
      pathname: url.pathname,
      search: url.search,
      hash: url.hash,
    };
  },
  createURL: createURL
});

const createHistoryRouter = (history: History) => (
    routes: RouteObject[],
    opts?: DOMRouterOpts
  ): RemixRouter => {
...
history: wrapHistory(history) ?? createBrowserHistory({ window: opts?.window }),
...
}
```

however when navigating using a Link component the callstack explodes. checking Redux devtools it looks like it's got stuck in a loop submitting @@router/LOCATION_CHANGE actions.


I looked at the notes for the methods I've added from the History type. I'll post here
```
(method) History.encodeLocation(to: To): Path
Encode a location the same way window.history would do (no-op for memory history) so we ensure our PUSH/REPLACE navigations for data routers behave the same as POP

@param to — Unencoded path

(method) History.createURL(to: To): URL
Returns a URL for the given to value

@param to — The destination URL
```

**Comment by CarreraPHP** [comment]
@kale1d0code, Hope you succeed with you attempt of making React router >= 6.4 to work with redux. 

But, I ask this question to the entire Redux community out there, Why can't we create or fork the React router V5 and make a Router that has Redux as its integral core logic. I think that would be the permanent solution.

Remix and Nextjs have their plans to support RSC and having not to expose history makes their work easier. The choice that the redux community has is to create a Router that works only through redux and on the client side. For rest of the case, just forget the router and have redux islands that work per page.

**Comment by elmarti** [comment]
I've got RRD V6 working with unstable_HistoryRouter - obviously not ideal and i'll be looking for a long term solution before production, but thought i'd share: 
```
import { unstable_HistoryRouter as HistoryRouter, Routes, Route } from "react-router-dom";
      <HistoryRouter history={history as any}>
 ....
```

**Comment by knownasilya** [comment]
@elmarti using actions and loaders?

**Comment by CarreraPHP** [comment]
@elmarti , @kale1d0code , I tried using HistoryRouter as a replacement of BroswerRouter but in that repo, we use connected-react-router package insteadof redux-first-history and it fails. Need to check, how i can migrate to redux-first-history package first.

But, can you guys confirm if history-router from React Router 6.20 is working well with redux-first-history?

**Comment by knownasilya** [comment]
@CarreraPHP 6.2 and probably even 6.4 works, just the loaders and actions do not work because you need a specific router for that.

**Comment by kale1d0code** [comment]
@CarreraPHP

I've created the following gist which I hope will help
https://gist.github.com/kale1d0code/6fec7abec7c921d67e7d4463f155d17d

**Comment by veeramarni** [comment]
@salvoravida thanks for the nice library. Can you please make this library support 6.4+ officially?

**Comment by cha0s** [comment]
Greetings! You may be interested in my project: https://github.com/cha0s/redux-data-router
